name: Continuous Deployment
run-name: Continuous Deployment
on:
  push:
    branches: [master, develop]
jobs:
  build-client:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG: ${{ steps.export_image_tag.outputs.IMAGE_TAG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Add SHORT_SHA to the environment
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | head -c 7)" >> $GITHUB_ENV
      - name: Extract Git Tag
        run: echo "IMAGE_TAG=$GITHUB_REF_NAME-$GITHUB_RUN_NUMBER-$SHORT_SHA" >> $GITHUB_ENV
      - name: Create .env file client
        run: echo "${{ secrets.ENV_CLIENT_STAGING }}" >> client/.env
      - name: Build the Docker image client
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG}}
        uses: docker/build-push-action@v5
        id: docker_build_client
        with:
          context: client
          file: ./client/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/smbpost-client:${{ env.IMAGE_TAG }}
      - name: Verify
        run: |
          echo IMAGE_TAG=$IMAGE_TAG
          echo ${{ steps.docker_build_client.outputs.digest }}
      - name: Export IMAGE_TAG to github output
        id: export_image_tag
        run: echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT
  build-server:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG: ${{ steps.export_image_tag.outputs.IMAGE_TAG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Add SHORT_SHA to the environment
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | head -c 7)" >> $GITHUB_ENV
      - name: Extract Git Tag
        run: echo "IMAGE_TAG=$GITHUB_REF_NAME-$GITHUB_RUN_NUMBER-$SHORT_SHA" >> $GITHUB_ENV
      - name: Create .env file server
        run: echo "${{ secrets.ENV_SERVER_STAGING }}" >> server/.env
      - name: Build the Docker image server
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG}}
        uses: docker/build-push-action@v5
        id: docker_build_server
        with:
          context: server
          file: ./server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/smbpost-server:${{ env.IMAGE_TAG }}
      - name: Verify
        run: |
          echo IMAGE_TAG=$IMAGE_TAG
          echo ${{ steps.docker_build_server.outputs.digest }}
      - name: Export IMAGE_TAG to github output
        id: export_image_tag
        run: echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT
  deploy-client:
    needs: build-client
    runs-on: ubuntu-latest
    steps:
      - name: Print IMAGE_TAG value
        run: echo "IMAGE_TAG value is ${{ needs.build-client.outputs.IMAGE_TAG }}"
      - name: executing remote ssh
        env:
          IMAGE_TAG: ${{ needs.build-client.outputs.IMAGE_TAG }}
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_PKEY }}
          port: ${{ secrets.DO_PORT }}
          script: |
            docker ps -q --filter "name=smbpost-client" | grep -q . && docker stop smbpost-client
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/smbpost-client:${{ env.IMAGE_TAG }}
            docker run -d -p 80:3000 --rm --name smbpost-client ${{ secrets.DOCKERHUB_USERNAME }}/smbpost-client:${{ env.IMAGE_TAG }}
  deploy-server:
    needs: build-server
    runs-on: ubuntu-latest
    steps:
      - name: Print IMAGE_TAG value
        run: echo "IMAGE_TAG value is ${{ needs.build-server.outputs.IMAGE_TAG }}"
      - name: executing remote ssh
        env:
          IMAGE_TAG: ${{ needs.build-server.outputs.IMAGE_TAG }}
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_PKEY }}
          port: ${{ secrets.DO_PORT }}
          script: |
            docker ps -q --filter "name=smbpost-server" | grep -q . && docker stop smbpost-server
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/smbpost-server:${{ env.IMAGE_TAG }}
            docker run -d -p 80:3000 --rm --name smbpost-server ${{ secrets.DOCKERHUB_USERNAME }}/smbpost-server:${{ env.IMAGE_TAG }}