name: Hello workflows
on:
  push:
    branches:
      - master

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: _Step_ setup node version 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: _Step_ checkout
        uses: actions/checkout@v3
      - name: _Step_ log file list
        run: ls -al
